In [1]:
import numpy as np

In [1]:
from __future__ import print_function
import torch

In [2]:
#创建一个5*3的矩阵
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
##随机初始化一个矩阵
x_random = torch.rand(5,3)
print(x_random)

tensor([[0.5587, 0.6011, 0.1607],
        [0.0135, 0.0260, 0.5441],
        [0.3917, 0.8434, 0.0431],
        [0.7827, 0.1167, 0.1080],
        [0.9713, 0.1819, 0.2145]])


In [4]:
#创建一个0填充的矩阵，数据类型为long
x_long = torch.zeros(5,3, dtype=torch.long)
print(x_long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
##创建tensor(张量矩阵)
x_tensor = torch.tensor([5.5, 3])
print(x_tensor)

tensor([5.5000, 3.0000])


In [7]:
##根据现有的张量(维度和数量)创建新的张量(维度和数量相同)。
x = x_tensor.new_ones(5,3, dtype=torch.double)  ##创建一个新对象，在之前的张量上(继承了这个对象)
print(x)

x = torch.randn_like(x, dtype=torch.float) ##继承tensor的size
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2548, -0.0500, -0.9239],
        [ 0.9588, -0.9675,  0.4927],
        [-0.5409, -0.5524,  1.8144],
        [-0.5791, -1.6736, -0.2182],
        [ 0.4325,  2.5892, -0.2272]])


In [11]:
##各种操作语法
y = torch.rand(5,1)   ###同样存在广播
print('y:\n')
print(y)

print('x+y:\n')
print(x + y)


y:

tensor([[0.0612],
        [0.5827],
        [0.1419],
        [0.4089],
        [0.9934]])
x+y:

tensor([[ 0.3160,  0.0113, -0.8627],
        [ 1.5415, -0.3848,  1.0754],
        [-0.3990, -0.4105,  1.9563],
        [-0.1703, -1.2648,  0.1906],
        [ 1.4259,  3.5826,  0.7662]])


In [12]:
torch.add(x, y)

tensor([[ 0.3160,  0.0113, -0.8627],
        [ 1.5415, -0.3848,  1.0754],
        [-0.3990, -0.4105,  1.9563],
        [-0.1703, -1.2648,  0.1906],
        [ 1.4259,  3.5826,  0.7662]])

In [18]:
###任何以‘_’结尾的操作都会用结果替换原变量，我(吕松科)觉得不好！！
y = torch.randn(5,3)
y_ = y.view(15)
y_ = y_.view(5,3)
y_.add_(x)
print(y_)

tensor([[-0.1382, -1.4314, -1.7900],
        [-0.4879, -0.4154,  1.6822],
        [-0.9179,  0.1184,  2.2554],
        [ 1.0950, -0.7271,  0.0160],
        [ 0.5137,  2.9146,  0.0053]])


In [20]:
if torch.cuda.is_available():
    print('存在 cuda')
else:
    print('不存在cuda')
#     device = torch.device('cuda')
#     y = torch.ones_like(x, device=device)

不存在cuda


In [21]:
###自动计算梯度，进行反向传播算法(bp)
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [22]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [23]:
z = y ** 2 * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [24]:
out.backward()

In [25]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [26]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [38]:
x = torch.tensor([1,1,1], requires_grad=True, dtype=torch.float)

y = x * 2
# while y.data.norm() < 1000:
#     y = y*2

print(y)

tensor([2., 2., 2.], grad_fn=<MulBackward0>)


In [33]:
y.data.norm()

tensor(1773.6200)

In [39]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)  ##传入的梯度时的x值
y.backward(gradients)

print(x.grad)

tensor([2.0000e-01, 2.0000e+00, 2.0000e-04])


In [30]:
x

tensor([-0.3538,  1.0040, -0.7025], requires_grad=True)